txtbld="$(tput bold)"    # BOLD
txtund="$(tput smul)"    # START UNDERLINE
txtnound="$(tput rmul)"  # STOP UNDERLINE
txtblk="$(tput setaf 0)" # Black - Regular
txtred="$(tput setaf 1)" # Red
txtgrn="$(tput setaf 2)" # Green
txtylw="$(tput setaf 3)" # Yellow
txtblu="$(tput setaf 4)" # Blue
txtpur="$(tput setaf 5)" # Purple
txtcyn="$(tput setaf 6)" # Cyan
txtwht="$(tput setaf 7)" # White
bakblk="$(tput setab 0)" # Black - Background
bakred="$(tput setab 1)" # Red
badgrn="$(tput setab 2)" # Green
bakylw="$(tput setab 3)" # Yellow
bakblu="$(tput setab 4)" # Blue
bakpur="$(tput setab 5)" # Purple
bakcyn="$(tput setab 6)" # Cyan
bakwht="$(tput setab 7)" # White
txtrst="$(tput sgr0)"    # Text Reset